controllers:
    resource:
        path: ../src/Controller/
        namespace: App\Controller
    type: attribute
    methods: [GET, POST, PUT, DELETE]

index:
    path: /
    controller: App\Controller\ReminderController::index